steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/build-image', '.' ]
  timeout: 500s
-name: 'gcr.io/$PROJECT_ID/build-image'
  args: ['git', 'clone', 'https://github.com/quinnabrvau/settlers_comp_player.git','project']
-name: 'gcr.io/$PROJECT_ID/build-image'
  args: ['make', 'test']
  dir: 'project'
images:
- 'gcr.io/$PROJECT_ID/build-image'
