steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['pull', 'gcr.io/cloud-builders/gcloud']
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/build-image', '.' ]
  timeout: 500s
# -name: 'gcr.io/$PROJECT_ID/build-image'
#   args: ['git', 'clone', 'https://github.com/quinnabrvau/settlers_comp_player.git','project']
#   timeout: 500s
# -name: 'gcr.io/$PROJECT_ID/build-image'
#   args: ['make', 'test']
#   dir: 'project'
#   timeout: 500s
images:
- 'gcr.io/$PROJECT_ID/build-image'
