steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['pull', 'gcr.io/cloud-builders/gcloud']
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '--tag=gcr.io/$PROJECT_ID/build-image', '.' ]
  timeout: 500s
- name: 'gcr.io/$PROJECT_ID/build-image'
  args: ['git', 'clone', 'https://github.com/quinnabrvau/settlers_comp_player.git']
  timeout: 500s
- name: 'gcr.io/$PROJECT_ID/build-image'
  args: ['make', 'test']
  timeout: 500s
images:
- 'gcr.io/$PROJECT_ID/build-image'
