steps:
- name: 'github.com/quinnabrvau/settlers_comp_player.git'
      args: ['fetch']
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/build-image', '.' ]
  timeout: 500s
images:
- 'gcr.io/$PROJECT_ID/build-image'